### ISSUE TITLE
mps-gradle plugin 1.4.+ cannot be found

### ISSUE THREAD

**Issue by ratiud** [mbeddr/mps-gradle-plugin#97] opened 2021-04-16 20:23 UTC
attached is a screenshot from building FASTEN

![image](https://user-images.githubusercontent.com/74968924/115079975-461d2c00-9f02-11eb-919f-7867dfbba479.png)

**Comment by vlsi** [comment] 2021-04-18 21:48
It might be caused by the missing jars and poms in the latest publication: https://projects.itemis.de/nexus/content/repositories/mbeddr/de/itemis/mps/mps-gradle-plugin/1.4.259.ea181a8/

I guess https://projects.itemis.de/nexus/content/repositories/mbeddr/de/itemis/mps/mps-gradle-plugin/1.4.258.d478f80/ would work for you.

**Comment by alexanderpann** [comment] 2023-01-30 16:18
I am closing this issue as we don't use the old nexus (projects.itemis.de) anymore.

**Closed by alexanderpann** 2023-01-30 16:18 UTC
